version: "2"

services:

  mysql:
    image: web-mysql
    container_name: web-mysql
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  redis:
    image: web-redis
    container_name: web-redis
    build: ./docker/redis

  web:
    image: web-app
    container_name: web-app
    build: ./docker/web
    volumes:
      - ./src:/var/www/html
    links:
      - mysql
      - redis

  nginx:
    image: web-nginx
    container_name: web-nginx
    build: ./docker/nginx
    volumes:
      - ./src/public:/var/www/html/public
      - ./src/storage/app/public:/var/www/html/storage/app/public
    ports:
      - "80:80"
      - "443:443"
    links:
      - web
